name: tipout_final
description: Tipout

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^4.0.6
  flutter_svg: ^1.1.5
  image_picker: ^0.8.6
  permission_handler: ^10.1.0
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  flutter_multi_formatter: ^2.8.2
  cached_network_image: ^3.2.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/